services:
  - type: web
    name: weather-dashboard-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: WEATHER_API_KEY
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /
    autoDeploy: true
